
=head1 QUIKI SYNTAX

Quiki wiki syntax is very similar to other wiki, and especially
similar with dokuwiki syntax.

=head2 Basics

=over 4

=item *

To force a paragraph give a blank line;

=item *

To refer to another node use: C<[[NodeName]]> or C<[[NodeName|Node Description]]>;

=item *

To link the Internet use just the URL and it should be highlighted

=item *

You can also create named links with: C<[[URL|URL Description]]>

=back

=head2 Basic formatting

=over 4

=item *

Bolds: C<**bold**>;

=item *

Italics: C<//italic//>;

=item *

Underlines: C<__underline__>;

=item *

Typewriter: C<< ''typewriter'' >>;

=back

=head2 Headings

=over 4

=item *

Stronger: C<====== title ======>

=item *

Weaker: C<= title =>

=back

=head2 Lists

=over 4

=item *

Ordered lists as a dash C<->

=item *

Unordered lists as an asterisk C<*>

=item *

Each item with two spaces before the mark

=item *

Deeper levels have multiples of two spaces indentation

=back

=head2 Tables

=over 4

=item *

Table headers separated by a carret character ^. Note that no space should exist in the beginning of the line.

=item *

Table rows separated by a pipe character |. Note that no space should exist in the beginning of the line.

=item *

Each cell (not header) will be formatted accordingly with the ascii alignment:

=over 4

=item *

put the content at the left without spaces, to get left alignment: C<< |foo | >>

=item *

put the content at the right without spaces, to get right alignment: C<< | foo| >>

=item *

put the content at the center, with spaces both sides, to get center alignment: C<< | foo | >>

=back

=back

=head2 Images

=over 4

=item *

Pictures are delimited by a pair or curly braces: C<< {{ http://www.google.com/images/logo.gif }} >>

=item *

You can add a description to the image. It will be used as alternative text (and tooltip text): C<< {{ http://www.google.com/images/logo.gif | Google logo }} >>

=item *

Alignment can be obtained with spaces:

=over 4

=item Default alignment

For the default alignment do not add any extra space after the opening pair of curly braces or before the closing pair of curly braces: C<< {{http://www.google.com/images/logo.gif}} >>

=item Centering

To center the image add spaces both sides, after the opening curly braces and before the closing curly braces: C<< {{  http://www.google.com/images/logo.gif }} >>

=item Float left

To float the image at the left add spaces  before the closing curly braces: C<< {{http://www.google.com/images/logo.gif }} >>

Note that if you have a description, spaces will go B<after> the descriptions, right before the closing braces.

=item Float right

To float the image at the right add spaces  after the opening curly braces: C<< {{  http://www.google.com/images/logo.gif}} >>

=back

=back

=head2 Attachments

Attachments follow the same philosophy of images but instead of the image URL you should add the attachment name preceded by C<< wiki: >> as: C<< {{wiki:picture|Picture of a dog}} >>.

=head2 Other

=over 4

=item *

Hard rules are obtained with ten or more dashes: C<--------------->

=item *

Code/verbatim zones are blocks with all lines indented three spaces.

=back


